# Generated by Django 5.1 on 2024-09-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow", "0002_borrow_check_borrow_date_before_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
